### PR TITLE
Sylt synchronized lyric support

### PR DESCRIPTION
**Pull request by tramhao**
Support synchronized lyric. It should be standard sylt format, but the problem is, I cannot find any other program to test. I can open it with kid3 without problem.

### CODE REVIEW

**Comment by issadarkthing** [comment]
What are the benefits of having this?

**Comment by tramhao** [comment]
It's supposed to comply with id3 sylt tags, so other player can play the mp3 files with synchronized lyrics. Because generally speaking unsynchronized lyrics doesn't have timestamp thus other player will not parse the timestamp we put in uslt like we do. Probably we'll be the 1st apps to support sylt under linux. Please check this out: https://cweiske.de/tagebuch/embedded-lyrics.htm

**Comment by issadarkthing** [comment]
Does the fetch lyric use sylt by default?

**Comment by issadarkthing** [comment]
> Probably we'll be the 1st apps to support sylt under linux.

This is great!
Seems like you are using your own fork of id3v2 library https://github.com/tramhao/id3v2. I have no problem with this as long as you are able to maintain the fork yourself.

Everything seems to working fine on my machine, fetch and delete lyrics work smoothly. If you've finished, please clean up the commented out code.

**Comment by tramhao** [comment]
> Does the fetch lyric use sylt by default?

Yes, sylt is selected by default and uslt is like a backup. I have a problem though, how to distinguish them? The language descriptor is the same.

**Comment by tramhao** [comment]
> > Probably we'll be the 1st apps to support sylt under linux.
> 
> This is great!
> Seems like you are using your own fork of id3v2 library https://github.com/tramhao/id3v2. I have no problem with this as long as you are able to maintain the fork yourself.
> 
> Everything seems to working fine on my machine, fetch and delete lyrics work smoothly. If you've finished, please clean up the commented out code.

For the fork, I want to make sure that the code is working well, then I'll try to submit to the upstream. After the author accept it, we could move to the official repo.

**Comment by tramhao** [comment]
Let me check related code more as it's just finished yesterday. Seems the getTagLength is changing mtime too.

**Comment by tramhao** [comment]
It should be all right now. Thanks.

**Comment by issadarkthing** [comment]
I will review this tonight

**Pull request merged**
