### PR TITLE
lyrics in progress bar

### PR DESCRIPTION
**Pull request by tramhao**
Currently the progress is:
1. Download subtitles(need to move language setting to config)
2. Edit tag and embed lyrics(need to check workflow, as currently enter key will close the popup, and could be triggered by user in many controls, also the lyric name displayed is not long enough, to show the language difference)
3. Display below progress bar.

Please check if it's all right and have a nice day.

### CODE REVIEW

**Comment by tramhao** [comment]
make test is not working.

**Comment by issadarkthing** [comment]
How do I pull up the lyrics?

**Comment by issadarkthing** [comment]
Does the `.srt` file still need to be around even after you have tag it in mp3 file?

**Comment by tramhao** [comment]
after tag, the srt file is no longer needed. 。we coul delete it

**Comment by issadarkthing** [comment]
I think the better approach will be adding the tag after you downloaded them. With this, you don't have to pick lyric file from the tag editor popup in order to embed lyric into the mp3 file.

**Comment by issadarkthing** [comment]
Other than that, the lyric shown on playing bar works like charm!

**Comment by tramhao** [comment]
> I think the better approach will be adding the lyric tag after you downloaded them. With this, you don't have to pick lyric file from the tag editor popup in order to embed lyric into the mp3 file.

Yes, I also think it's better. But I also have some concerns. I want to put the prefered language into config, like:
lang_lyric = en, zh-Hans
this way, there will be 2 srt files being downloaded. After that, I could choose which lyric to embed in tag edit popup. (Because sometimes I download english songs as well.) 
How about this:
we download 2 files, embed one by default and delete it. For the other one, could be used as another option when edit tag.
Or should we download all lyrics available? Considering some spanish songs are also quite popular. Although I cannot understand it all, the spanish lyric is easy to pronounce.

**Comment by issadarkthing** [comment]
> should we download all lyrics available? Considering some spanish songs are also quite popular. Although I cannot understand it all, the spanish lyric is easy to pronounce.

I agree with downloading all language lyrics but I think it should embed user preferred language to the audio file or english by default. Deleting any of the lyrics file should not be done since the user may want to change the language in the future.

As for tag editor, `lyrics available` field should only show the language of the lyric file that is related to the audio and should not clutter with other `.srt` file. Or better, just show the list of available language since it is more intuitive.

**Comment by tramhao** [comment]
> > should we download all lyrics available? Considering some spanish songs are also quite popular. Although I cannot understand it all, the spanish lyric is easy to pronounce.
> 
> I agree with downloading all language lyrics but I think it should embed user preferred language to the audio file or english by default. Deleting any of the lyrics file should not be done since the user might want to change the language in the future.
> 
> As for tag editor, `lyrics available` field should only show the language of the lyric file that is related to the audio and should not clutter with other `.srt` file. Or better, just show the list of available language since it is more intuitive.

Totally agree and I'll do that.

**Comment by tramhao** [comment]
> > should we download all lyrics available? Considering some spanish songs are also quite popular. Although I cannot understand it all, the spanish lyric is easy to pronounce.
> 
> I agree with downloading all language lyrics but I think it should embed user preferred language to the audio file or english by default. Deleting any of the lyrics file should not be done since the user might want to change the language in the future.
> 
> As for tag editor, `lyrics available` field should only show the language of the lyric file that is related to the audio and should not clutter with other `.srt` file. Or better, just show the list of available language since it is more intuitive.

Just figure out a better way to do it. After reading the code of id3v2, actually we could write all languages into mp3 as long as languang+content descriptor are not fully identical. This way we could avoid manually editing lyric tag and can switch lyrics during playing!

**Comment by issadarkthing** [comment]
> Just figure out a better way to do it. After reading the code of id3v2, actually we could write all languages into mp3 as long as languang+content descriptor are not fully identical. This way we could avoid manually editing lyric tag and can switch lyrics during playing!

Seems fine to me

**Comment by issadarkthing** [comment]
I'm sorry for being picky but can you add a single space after `//` like this `// this is comment` instead of this `//this is comment`

**Comment by tramhao** [comment]
sure. no problem

**Review by tramhao — COMMENTED** [review]
I have an embedlyric function in playlist.go and you can use it

**Comment by issadarkthing** [comment]
> I have an embedlyric function in playlist.go and you can use it

Yeah, but the function requires a file and `lyric.GetLyric` returns string. I suggest `EmbedLyric` to change the `lyricFile` to accept the file content in string instead of the file name. This will make `EmbedLyric` easier to be tested. I also suggest `EmbedLyric` should be in lowercase `embedLyric` to make it explicit that it will be used in `main` package.

I am aware that there are inconsistencies in the code base, I will make the code contribution guideline after this pull request is tested and merged.

**Comment by issadarkthing** [comment]
The `lyrics available` field in tag editor popup does not show any option at all even though there are 2 lyrics in different language are embedded.

**Comment by tramhao** [comment]
Yes, that dialogue only show downloaded lyric files, not embeded lyrics. In the new implementation , what should we do with this dropdown? I haven't change it yet.

**Comment by tramhao** [comment]
> > I have an embedlyric function in playlist.go and you can use it
> 
> Yeah, but the function requires a file name and `lyric.GetLyric` returns string. I suggest `EmbedLyric` to change the `lyricFile` to accept the file content in string instead of the file name. This will make `EmbedLyric` easier to be tested. I also suggest `EmbedLyric` should be in lowercase `embedLyric` to make it explicit that it will only be used in `main` package.
> 
> I am aware that there are inconsistencies in the code base, I will make the code contribution guideline after this pull request is tested and merged.

yes I should change it to accept strings instead of files.

**Comment by tramhao** [comment]
maybe we should refactoring the functions and variables sometime.

**Comment by issadarkthing** [comment]
> Yes, that dialogue only show downloaded lyric files, not embeded lyrics. In the new implementation , what should we do with this dropdown? I haven't change it yet.

I think we should totally remove it since it will be more confusing

**Comment by issadarkthing** [comment]
> maybe we should refactoring the functions and variables sometime.

Yup, totally agree with that.

**Comment by tramhao** [comment]
> > Yes, that dialogue only show downloaded lyric files, not embeded lyrics. In the new implementation , what should we do with this dropdown? I haven't change it yet.
> 
> I think we should totally remove it since it will be more confusing

Yes and I think it'll keep the program simple and nice.

**Comment by tramhao** [comment]
a little problem. The fetch lyric function works great for English song names, but not working for chinese. Is it a limitation of the website?

**Comment by issadarkthing** [comment]
yeah it seems the website only provide lyric for english songs

**Comment by issadarkthing** [comment]
If everything seems okay, I will merge this pr

**Comment by tramhao** [comment]
> If everything seems okay, I will merge this pr

One moment, I'm checking the parse method of subtitle package, and seems it can support many formats of lyrics automatically. Perhaps we should bring back the manually add lyric function so it's more flexible.

**Comment by tramhao** [comment]
> > If everything seems okay, I will merge this pr
> 
> One moment, I'm checking the parse method of subtitle package, and seems it can support many formats of lyrics automatically. Perhaps we should bring back the manually add lyric function so it's more flexible.

I gave up. The parse method of subtitle package need []byte as input. When I use []byte(uslf.Lyrics) , everything is working for english subtitles, but for chinese subtitles, the encoding is messed up. Please merge the PR as what we've done now and leave this parse method for the future.

**Pull request merged**
